=== bhavya815/EP-PRACTICAL/EP PRACTICAL/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="students">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="student" minOccurs="0"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="idno" type="xs:string" />
							<xs:element name="name" type="xs:string" />
							<xs:element name="marks" type="xs:byte" />
							<xs:element name="email" type="xs:string" />
							<xs:element name="class" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bhavya815/EP-PRACTICAL/EP PRACTICAL/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="students.xsd">
	<student>
		<idno>0821</idno>
		<name>Bhavya sri</name>
		<marks>90</marks>
		<email>bhavyasrinivas999@gmail.com</email>
		<class>1</class>
	</student>
	<student>
		<idno>2108</idno>
		<name>Sai Siva Nandha Reddy</name>
		<marks>91</marks>
		<email>sai@gmail.com</email>
		<class>2</class>
	</student>
	<student>
		<idno>2277</idno>
		<name>Hasma</name>
		<marks>92</marks>
		<email>Hasmasyed22@gmail.com</email>
		<class>4</class>
	</student>
	<student>
		<idno>1233</idno>
		<name> Mahesh</name>
		<marks>94</marks>
		<email>mahesh21@gmail.com</email>
		<class>5</class>
	</student>
	<student>
		<idno>005</idno>
		<name>Arjun</name>
		<marks>95</marks>
		<email>Arjun@gmail.com</email>
		<class>6</class>
	</student>
</students>
